web:
  build: .
  command: ember serve
  links:
    - 'api'
  ports:
    - '4200:4200'
    - '35729:35729'
  volumes:
    - '.:/home/dev/docker-webui'
  environment:
    - API_URL

api:
  image: containerhq/arkis-api:1.0.0.alpha
  command: node index.js
  user: root
  ports:
    - '4000:4000'
  links:
    - 'db'
  volumes:
    - '$DOCKER_CERT_PATH:/home/.docker'
    - '/var/run/docker.sock:/var/run/docker.sock'
  environment:
    - DOCKER_CERT_PATH=/home/.docker
    - DOCKER_HOST
    - DOCKER_TLS_VERIFY

db:
  image: postgres:9.4.2
  expose:
    - '5432'
  volumes:
    - '/arkis-db:/var/lib/postgresql/data'
