web:
  build: .
  command: ember serve
  links:
    - 'api'
  ports:
    - '4200:4200'
    - '35729:35729'
  volumes:
    - '.:/home/dev/docker-webui'
  environment:
    - API_URL

api:
  image: foliea/docker-proxy:latest
  command: node index.js
  ports:
    - '4000:4000'
  volumes:
    - '$DOCKER_CERT_PATH:/home/.docker'
    - '/var/run/docker.sock:/var/run/docker.sock'
  environment:
    - DOCKER_CERT_PATH=/home/.docker
    - DOCKER_HOST
    - DOCKER_TLS_VERIFY
